spring.application.name=buyme
spring.config.import=optional:file:.env[.properties]

server.port=9090

spring.mongodb.uri=mongodb://localhost:27017/buyme_db

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

api.prefix=/api/v1

app.use-secure-cookie=false

## 1 min
#auth.token.access-expiration-in-mils=60000
## 3 days
#auth.token.refresh-expiration-in-mils=300000000

## 10 hrs
auth.token.access-expiration-in-mils=36000000
## 30 days
auth.token.refresh-expiration-in-mils=2592000000

auth.token.secret=yK/YUDsjYIguSdNb2Wf/arFZYZU7DzYqRpOMrZnE+BinwLC0YyeT8Bf51F44nzlWk+ZOl5fzuYbrfSxTZyMcfQ==
#auth.token.secret=FJbGf6dKlbudHEvFfobvN8J6RkecWzLIlfgyI3g5u9IlLUINWfouVgcksHUyv7NFgpSoZITMF92/zi0n

spring.output.ansi.enabled=ALWAYS

### stripe section
stripe.secret.key=${STRIPE_SECRET_KEY}