spring.application.name=buyme

server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/buyme_db

spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

api.prefix=/api/v1

app.use-secure-cookie=false

## 1 min
#auth.token.access-expiration-in-mils=60000
## 3 days
#auth.token.refresh-expiration-in-mils=300000000

## 10 hrs
auth.token.access-expiration-in-mils=36000000
## 30 days
auth.token.refresh-expiration-in-mils=2592000000

auth.token.secret=yK/YUDsjYIguSdNb2Wf/arFZYZU7DzYqRpOMrZnE+BinwLC0YyeT8Bf51F44nzlWk+ZOl5fzuYbrfSxTZyMcfQ==
#auth.token.secret=FJbGf6dKlbudHEvFfobvN8J6RkecWzLIlfgyI3g5u9IlLUINWfouVgcksHUyv7NFgpSoZITMF92/zi0n

spring.output.ansi.enabled=ALWAYS

### stripe section
stripe.secret.key=YOUR_STRIPE_SECRET_KEY_HERE