spring.application.name=buyme
spring.config.import=optional:file:.env[.properties]

server.port=9090

spring.mongodb.uri=mongodb://localhost:27017/buyme_db

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

api.prefix=/api/v1

app.use-secure-cookie=false

## 1 min
#auth.token.access-expiration-in-mils=60000
## 3 days
#auth.token.refresh-expiration-in-mils=300000000

## 10 hrs
auth.token.access-expiration-in-mils=36000000
## 30 days
auth.token.refresh-expiration-in-mils=2592000000

auth.token.secret=${JWT_SECRET_KEY}

spring.output.ansi.enabled=ALWAYS

### stripe section
stripe.secret.key=${STRIPE_SECRET_KEY}

### openai section
spring.ai.openai.api-key=${OPENAI_API_KEY}

#### chroma section
spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.collection-name=image_collection
spring.ai.vectorstore.chroma.initialize-schema=true